apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podpreset-webhook
subjects:
  - kind: ServiceAccount
    name: podpreset-webhook
    namespace: ${PROJECT_NAME}
roleRef:
  kind: ClusterRole
  name: podpreset-webhook
  apiGroup: rbac.authorization.k8s.io
