apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-php
  namespace: ${PROJECT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-php
      role: frontend
  template:
    metadata:
      labels:
        app: welcome-php
        role: frontend
    spec:
      containers:
      - name: welcome-php
        image: quay.io/redhatworkshops/welcome-php:latest
